ports = []
[languages.go]
language = "go"
[languages.go.run."myNameVar.go"]
name = "myNameVar.go"
path = "/workspace/GolangTrainingCamp/03_variables/03_less-emphasis/08_exercise_your-name/04_anotherSolution/myNameVar.go"

[languages.go.run."variables.go"]
name = "variables.go"
path = "/workspace/GolangTrainingCamp/03_variables/03_less-emphasis/07_all-together/variables.go"

[languages.go.run."var.go"]
name = "var.go"
path = "/workspace/GolangTrainingCamp/03_variables/03_less-emphasis/06_init-shorthand/var.go"

[languages.go.run."type.go"]
name = "type.go"
path = "/workspace/GolangTrainingCamp/11_switch-statements/05_on-type/type.go"

[languages.go.run."main.go"]
name = "main.go"
path = "/workspace/GolangTrainingCamp/11_switch-statements/04_no-expression/main.go"
